version: "3.2"
services:
  ipld-eth-db:
    restart: always
    build:
      context: ${vulcanize_ipld_eth_db}/
    environment:
      POSTGRES_USER: vdbm
      POSTGRES_DB: vulcanize_testing
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:8077:5432"
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]
