version: "3.2"
services:
  foundry:
    restart: unless-stopped
    depends_on:
      - ipld-eth-db
      - prometheus
    build: ../
    privileged: true
    environment:
      DB_USER: vdbm
      DB_NAME: vulcanize_testing
      DB_HOST: ipld-eth-db
      DB_PORT: 5432
      DB_PASSWORD: password
      DB_WRITE: "true"
      DB_TYPE: postgres
      DB_DRIVER: sqlx
      DB_WAIT_FOR_SYNC: "true"
      CHAIN_ID: "99"
      USE_GENESIS: "true"
      EXTRA_START_ARGS: "--metrics --metrics.expensive --metrics.addr 0.0.0.0 --metrics.port 6060"
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
      - "127.0.0.1:6060:6060"
  ipld-eth-db:
    restart: always
    build:
      context: ${vulcanize_ipld_eth_db}/
    environment:
      POSTGRES_USER: vdbm
      POSTGRES_DB: vulcanize_testing
      POSTGRES_PASSWORD: password
    volumes:
      - vdb_db_eth_server:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:8077:5432"
    command: ["postgres", "-c", "log_statement=all"]
  # YOU MUST UPDATE THE ops/metrics/env/prometheus.yml file to use foundry:6060 instead of localhost:6060
  prometheus:
    restart: always
    user: "987"
    image: prom/prometheus
    volumes:
      - ${vulcanize_ops}/metrics/etc:/etc/prometheus
      - ./prometheus-data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
  grafana:
    restart: always
    user: "472"
    image: grafana/grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
volumes:
  vdb_db_eth_server:
